INSERT INTO oauthClient (
  id,
  clientId,
  clientSecret,
  disabled,
  skipConsent,
  enableEndSession,
  subjectType,
  scopes,
  createdAt,
  updatedAt,
  name,
  redirectUris,
  postLogoutRedirectUris,
  tokenEndpointAuthMethod,
  grantTypes,
  responseTypes,
  public,
  type,
  requirePKCE,
  metadata
) VALUES (
  '00000000-0000-4000-8000-0000000000d1',
  'pg72-diary',
  'JBGEBuVX6hIOrc9Ez8mmMAZ8Yz2Jb5KRd1h6uZuhF54',
  0,
  0,
  1,
  'public',
  '["openid","profile","email"]',
  datetime('now'),
  datetime('now'),
  'PG72 Diary',
  '["https://diary.pg72.tw/api/auth/callback"]',
  '["https://diary.pg72.tw/"]',
  'client_secret_post',
  '["authorization_code"]',
  '["code"]',
  0,
  'web',
  1,
  '{"backchannel_logout_uri":"https://diary.pg72.tw/api/auth/backchannel-logout","developer_name":"PG72 官方"}'
)
ON CONFLICT(clientId) DO UPDATE SET
  clientSecret = excluded.clientSecret,
  disabled = 0,
  skipConsent = 0,
  enableEndSession = 1,
  scopes = excluded.scopes,
  name = excluded.name,
  redirectUris = excluded.redirectUris,
  postLogoutRedirectUris = excluded.postLogoutRedirectUris,
  tokenEndpointAuthMethod = excluded.tokenEndpointAuthMethod,
  grantTypes = excluded.grantTypes,
  responseTypes = excluded.responseTypes,
  public = excluded.public,
  type = excluded.type,
  requirePKCE = excluded.requirePKCE,
  metadata = excluded.metadata,
  updatedAt = datetime('now');

INSERT INTO oauthClient (
  id,
  clientId,
  clientSecret,
  disabled,
  skipConsent,
  enableEndSession,
  subjectType,
  scopes,
  createdAt,
  updatedAt,
  name,
  redirectUris,
  postLogoutRedirectUris,
  tokenEndpointAuthMethod,
  grantTypes,
  responseTypes,
  public,
  type,
  requirePKCE,
  metadata
) VALUES (
  '00000000-0000-4000-8000-0000000000d2',
  'pg72-diary-dev',
  NULL,
  0,
  0,
  1,
  'public',
  '["openid","profile","email"]',
  datetime('now'),
  datetime('now'),
  'PG72 Diary (local dev)',
  '["http://127.0.0.1:5173/api/auth/callback","http://localhost:5173/api/auth/callback"]',
  '["http://127.0.0.1:5173/","http://localhost:5173/"]',
  'none',
  '["authorization_code"]',
  '["code"]',
  1,
  'web',
  1,
  '{"developer_name":"PG72 官方"}'
)
ON CONFLICT(clientId) DO UPDATE SET
  clientSecret = excluded.clientSecret,
  disabled = 0,
  skipConsent = 0,
  enableEndSession = 1,
  scopes = excluded.scopes,
  name = excluded.name,
  redirectUris = excluded.redirectUris,
  postLogoutRedirectUris = excluded.postLogoutRedirectUris,
  tokenEndpointAuthMethod = excluded.tokenEndpointAuthMethod,
  grantTypes = excluded.grantTypes,
  responseTypes = excluded.responseTypes,
  public = excluded.public,
  type = excluded.type,
  requirePKCE = excluded.requirePKCE,
  metadata = excluded.metadata,
  updatedAt = datetime('now');
