INSERT INTO oauthClient (
  id,
  clientId,
  clientSecret,
  disabled,
  skipConsent,
  enableEndSession,
  subjectType,
  scopes,
  createdAt,
  updatedAt,
  name,
  redirectUris,
  postLogoutRedirectUris,
  tokenEndpointAuthMethod,
  grantTypes,
  responseTypes,
  public,
  type,
  requirePKCE
) VALUES (
  '00000000-0000-4000-8000-000000000072',
  'pg72-test-rp',
  NULL,
  0,
  0,
  1,
  'public',
  '["openid","profile","email","offline_access"]',
  datetime('now'),
  datetime('now'),
  'PG72 OIDC Test RP',
  '["http://localhost:5174/callback"]',
  '["http://localhost:5174/"]',
  'none',
  '["authorization_code","refresh_token"]',
  '["code"]',
  1,
  'web',
  1
)
ON CONFLICT(clientId) DO UPDATE SET
  disabled = 0,
  skipConsent = 0,
  enableEndSession = 1,
  scopes = excluded.scopes,
  name = excluded.name,
  redirectUris = excluded.redirectUris,
  postLogoutRedirectUris = excluded.postLogoutRedirectUris,
  tokenEndpointAuthMethod = excluded.tokenEndpointAuthMethod,
  grantTypes = excluded.grantTypes,
  responseTypes = excluded.responseTypes,
  public = excluded.public,
  type = excluded.type,
  requirePKCE = excluded.requirePKCE,
  updatedAt = datetime('now');
